/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jprova.view;

import javax.swing.JOptionPane;
import jprova.view.cadastro.CadastroDeAlunoView;
import jprova.view.cadastro.CadastroDeProfessorView;
import jprova.view.consulta.ConsultaDeAlunoView;
import jprova.view.consulta.ConsultaDeProfessorView;

/**
 *
 * @author Administrador
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPanePrincipal = new javax.swing.JTabbedPane();
        menuPrincipal = new javax.swing.JMenuBar();
        menuArquivo = new javax.swing.JMenu();
        menuItemSair = new javax.swing.JMenuItem();
        menuCadastro = new javax.swing.JMenu();
        menuItemAluno = new javax.swing.JMenuItem();
        menuItemProfessor = new javax.swing.JMenuItem();
        menuConsulta = new javax.swing.JMenu();
        menuItemAlunoC = new javax.swing.JMenuItem();
        MenuItemProfessorC = new javax.swing.JMenuItem();
        menuAjuda = new javax.swing.JMenu();
        menuSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JProva");
        setName("telaPrincipal"); // NOI18N

        menuPrincipal.setBackground(new java.awt.Color(204, 204, 204));

        menuArquivo.setText("Fechar");

        menuItemSair.setText("Sair");
        menuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSairActionPerformed(evt);
            }
        });
        menuArquivo.add(menuItemSair);

        menuPrincipal.add(menuArquivo);

        menuCadastro.setText("Cadastro");

        menuItemAluno.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemAluno.setText("Cadastro de Aluno");
        menuItemAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAlunoActionPerformed(evt);
            }
        });
        menuCadastro.add(menuItemAluno);

        menuItemProfessor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemProfessor.setText("Cadastro de Professor");
        menuItemProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemProfessorActionPerformed(evt);
            }
        });
        menuCadastro.add(menuItemProfessor);

        menuPrincipal.add(menuCadastro);

        menuConsulta.setText("Consulta");

        menuItemAlunoC.setText("Consulta Aluno");
        menuItemAlunoC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAlunoCActionPerformed(evt);
            }
        });
        menuConsulta.add(menuItemAlunoC);

        MenuItemProfessorC.setText("Consulta Professor");
        MenuItemProfessorC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemProfessorCActionPerformed(evt);
            }
        });
        menuConsulta.add(MenuItemProfessorC);

        menuPrincipal.add(menuConsulta);

        menuAjuda.setText("Ajuda");

        menuSobre.setText("Sobre");
        menuSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSobreActionPerformed(evt);
            }
        });
        menuAjuda.add(menuSobre);

        menuPrincipal.add(menuAjuda);

        setJMenuBar(menuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPanePrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 707, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPanePrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAlunoActionPerformed
        // TODO add your handling code here:
        /* Codigo para acionar uma nova aba no painel tabulado da tela principal toda vez que o item menu for acionado*/
        tabbedPanePrincipal.add("Cadastro de aluno",
        new CadastroDeAlunoView(tabbedPanePrincipal));
        tabbedPanePrincipal.revalidate();
        tabbedPanePrincipal.repaint();
    }//GEN-LAST:event_menuItemAlunoActionPerformed

    private void menuItemProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemProfessorActionPerformed
        // TODO add your handling code here:
        tabbedPanePrincipal.add("Cadastro de Professor",
        new CadastroDeProfessorView(tabbedPanePrincipal));
        tabbedPanePrincipal.revalidate();
        tabbedPanePrincipal.repaint();
    }//GEN-LAST:event_menuItemProfessorActionPerformed

    private void menuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSairActionPerformed
        // TODO add your handling code here:
        /* Codigo exibe uma mensagem na tela perguntando se o usuário deseja mesmo fechar o sistema, caso seja escolhida a
        opção sim o sistema será fechado.
        */
        if (JOptionPane.showConfirmDialog(this,
                "Deseja mesmo fechar o sistema?","Confirmação",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_menuItemSairActionPerformed

    private void menuSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSobreActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,
         "JProva\n\nVersão 1.0\nCopyright: Breno Cesar",
         "Sobre", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_menuSobreActionPerformed

    private void menuItemAlunoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAlunoCActionPerformed
        // TODO add your handling code here:
        tabbedPanePrincipal.add("Consulta de aluno",
        new ConsultaDeAlunoView(tabbedPanePrincipal));
        tabbedPanePrincipal.revalidate();
        tabbedPanePrincipal.repaint();
    }//GEN-LAST:event_menuItemAlunoCActionPerformed

    private void MenuItemProfessorCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemProfessorCActionPerformed
        // TODO add your handling code here:
        tabbedPanePrincipal.add("Consulta de professor",
        new ConsultaDeProfessorView(tabbedPanePrincipal));
        tabbedPanePrincipal.revalidate();
        tabbedPanePrincipal.repaint();
    }//GEN-LAST:event_MenuItemProfessorCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuItemProfessorC;
    private javax.swing.JMenu menuAjuda;
    private javax.swing.JMenu menuArquivo;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenu menuConsulta;
    private javax.swing.JMenuItem menuItemAluno;
    private javax.swing.JMenuItem menuItemAlunoC;
    private javax.swing.JMenuItem menuItemProfessor;
    private javax.swing.JMenuItem menuItemSair;
    private javax.swing.JMenuBar menuPrincipal;
    private javax.swing.JMenuItem menuSobre;
    private javax.swing.JTabbedPane tabbedPanePrincipal;
    // End of variables declaration//GEN-END:variables
}
