/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package jprova.view.consulta;

import java.awt.Point;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import javax.swing.table.DefaultTableModel;
import jprova.controller.AlunoController;
import jprova.model.Aluno;

/**
 *
 * @author Administrador
 */
public class ConsultaDeAlunoView extends javax.swing.JPanel {
private JTabbedPane tabbedPane;
    /**
     * Creates new form ConsultaDeAlunoView
     */
    public ConsultaDeAlunoView(JTabbedPane tabbedPane1) {
        this.tabbedPane = tabbedPane1;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu = new javax.swing.JPopupMenu();
        menuItemApagar = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jTNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTNumero = new javax.swing.JTextField();
        jBConsulta = new javax.swing.JButton();
        jBFechar = new javax.swing.JButton();
        jSResultados = new javax.swing.JScrollPane();
        jTResultados = new javax.swing.JTable();

        menuItemApagar.setText("Apagar");
        menuItemApagar.setToolTipText("null");
        menuItemApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemApagarActionPerformed(evt);
            }
        });
        popupMenu.add(menuItemApagar);

        jLabel1.setText("Consulta De Aluno:");

        jLabel2.setText("Nome:");

        jLabel3.setText("Telefone:");

        jTNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTNumeroActionPerformed(evt);
            }
        });

        jBConsulta.setText("Consultar");
        jBConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConsultaActionPerformed(evt);
            }
        });

        jBFechar.setText("Fechar");
        jBFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFecharActionPerformed(evt);
            }
        });

        jTResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Telefone", "Curso"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTResultados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTResultadosMouseClicked(evt);
            }
        });
        jSResultados.setViewportView(jTResultados);
        if (jTResultados.getColumnModel().getColumnCount() > 0) {
            jTResultados.getColumnModel().getColumn(0).setResizable(false);
            jTResultados.getColumnModel().getColumn(1).setResizable(false);
            jTResultados.getColumnModel().getColumn(2).setResizable(false);
            jTResultados.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jBConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(48, 48, 48)
                            .addComponent(jBFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(jTNome, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(65, 65, 65)
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jSResultados, javax.swing.GroupLayout.PREFERRED_SIZE, 662, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jTNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBConsulta)
                            .addComponent(jBFechar))))
                .addGap(18, 18, 18)
                .addComponent(jSResultados, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTNumeroActionPerformed

    private void jBConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConsultaActionPerformed
        // TODO add your handling code here:
        AlunoController pc = new AlunoController();
        try{
            List<Aluno> listaDeAlunos = pc.buscar(
                jTNome.getText(),
                jTNumero.getText());
            DefaultTableModel model =
                    (DefaultTableModel) jTResultados.getModel();
            for (int i = model.getRowCount() - 1; i >= 0; i--) {
                model.removeRow(i);
            }
            if (listaDeAlunos != null) {
                for (int i = 0; i < listaDeAlunos.size(); i++) {
                    Aluno aluno = listaDeAlunos.get(i);
                    String[] p = new String[]{
                        String.valueOf(aluno.getId()),
                        aluno.getNome(),
                        aluno.getTelefone(),
                        aluno.getCurso()};
                    model.insertRow(i, p);
                }
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,
                "Não foi possivel consultar os alunos!\n\n"
                + e.getLocalizedMessage());
        }
        
            
    
    }//GEN-LAST:event_jBConsultaActionPerformed

    private void jBFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFecharActionPerformed
        // TODO add your handling code here:
        tabbedPane.remove(this);
        tabbedPane.validate();
        tabbedPane.repaint();
    }//GEN-LAST:event_jBFecharActionPerformed

    private void jTResultadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTResultadosMouseClicked
        // TODO add your handling code here:
        try{
            if (evt.getButton() == MouseEvent.BUTTON3){
                Point p = evt.getPoint();
                int row = jTResultados
                        .rowAtPoint(p);
                if (row >= 0 && row < jTResultados
                        .getRowCount()){
                    jTResultados.
                            setRowSelectionInterval(row, row);
                    popupMenu.show(evt.getComponent(),
                            evt.getX(), evt.getY());
                }
            }
        }catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Não foi Possivel abrir o popup!\n\n"
            + e.getLocalizedMessage());
        }
    }//GEN-LAST:event_jTResultadosMouseClicked

    private void menuItemApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemApagarActionPerformed
        // TODO add your handling code here:
        try {
            int row = jTResultados.getSelectedRow();
            AlunoController pc = new AlunoController();
            DefaultTableModel model = 
                    (DefaultTableModel) jTResultados
                    .getModel();
            if (JOptionPane.showConfirmDialog(this,
                    "Deseja mesmo apagar o paciente? "
                     + model.getValueAt(row, 1).toString(),
                    "Confirmação",
                    JOptionPane.YES_NO_OPTION) == 
                    JOptionPane.YES_OPTION) {   
            pc.excluir(Integer.parseInt(model.
                    getValueAt(row, 0).toString()));
            ((DefaultTableModel) jTResultados
                    .getModel()).removeRow(row);
        
           ((DefaultTableModel) jTResultados
                   .getModel()).removeRow(row);
        }
        } catch(Exception e){
            JOptionPane.showMessageDialog(this,
                    "Não foi possivel apagar o paciente \n\n"
            + e.getLocalizedMessage());
        }
    
    }//GEN-LAST:event_menuItemApagarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBConsulta;
    private javax.swing.JButton jBFechar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jSResultados;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTNome;
    private javax.swing.JTextField jTNumero;
    private javax.swing.JTable jTResultados;
    private javax.swing.JMenuItem menuItemApagar;
    private javax.swing.JPopupMenu popupMenu;
    // End of variables declaration//GEN-END:variables
}
